FROM node:16-alpine

WORKDIR /CLIENT_APP_SOURCE

RUN apk add --no-cache autoconf automake file g++ libtool make nasm libpng-dev

COPY package*.json .

RUN npm install --force

COPY . .

CMD ["npm", "run", "watch"]
