version: "3.8"
services:
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        container_name: "ALIVEWELL_SERVER_CONTAINER"
        networks:
            - NETWORK
        environment:
            NODE_ENV: production
        restart: unless-stopped
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile.production
        container_name: "ALIVEWELL_CLIENT_CONTAINER"
        networks:
            - NETWORK
        depends_on:
            -   server
networks:
    NETWORK:
        name: NETWORK
